//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroAssistant.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public long postId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string blurbText { get; set; }
        public byte[] Photo { get; set; }
        public string Video { get; set; }
        public decimal Price { get; set; }
        public string Phone { get; set; }
        public string City { get; set; }
        public long CategoryId { get; set; }
        public long StateId { get; set; }
        public long CountryId { get; set; }
        public System.DateTime PublishDate { get; set; }
        public System.DateTime ClosingDate { get; set; }
        public int IsbestOffer { get; set; }
        public int IsFree { get; set; }
        public int IsPublish { get; set; }
        public int IsActive { get; set; }
        public int IsDeleted { get; set; }
        public int JobHits { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string CreatedBy { get; set; }
        public string remark { get; set; }
        public long UserId { get; set; }
    }
}
