//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroAssistant.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisteredUser
    {
        public long UserID { get; set; }
        public string UserName { get; set; }
        public string usrPassword { get; set; }
        public string usrEmail { get; set; }
        public int IsActive { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string Website { get; set; }
        public string usrImage { get; set; }
        public int IsDeleted { get; set; }
        public int IsVerified { get; set; }
    }
}
